### ISSUE TITLE
Multiple monitor support?

### ISSUE THREAD

**Issue by larryebaum** [aaron-elkins/Vill-Q-Issues#1]
Seems to only work on one display in a multi-display setup...

**Comment by orklann** [comment]
Hello @larryebaum ,

(I've sent you a reply email, and this is a copy of that mail)

Yes, Vill Q will not let you draw things on both built-in and external display at the same time by now. but suppose you want to draw on external display, just run Vill Q at the external display (That’s to say click Vill Q.app on the Applications folder or something like that on the external display), so that you can draw on your external display. 

BTW, in multi-display the tool box window acts strangely, it hides from one display and shows up in the other display (This will be an easy fix next update)

So do you think which way is better:

1) Vill Q let user draw on the display which it’s opened (This is the one I tell you above)
2) Vill Q let user draw on both external display and built-in display at the same time no matter which display it’s opened. (This is not yet support now)

Let me know your choice, I just can not make an decision.

(Maybe a major update will coming a few days later according to this discussion on this feature)

**Comment by orklann** [comment]
@larryebaum 

I got an idea while I was having diner. Let me explain it to you, it’s quite simple.

Because the Vill Q menu bar icon will appears in all display (both external and built-in), So If the user want to draw on one display, what he need to do is clicking on the Vill Q menu bar icon on that display, and a tool box window will show up, and then he can use tools on the tool box to draw on that display. And what if he need to draw on the other display, he can just do the same on the other display.

I think this is the simplest way to support multi-display.
What do you think?

**Comment by orklann** [comment]
Issue solved. Closed.

**Comment by Krumelur** [comment]
I'd like to reopen this because it is not/no longer working. I'm on macOS High Sierra and the 2nd screen is a Thunderbolt connected monitor. No matter which icon I click, I can only draw on the main monitor. Also, I'd like to keep using my hotkeys to activate Vill Q - using the icon is not really an option. Maybe there is a better way to fix this.

**Comment by orklann** [comment]
@Krumelur I replied you via email, and because it's fixed, so I want to close this issue.
